---

- name: Install Gems
  tags:
    - gems
  gem:
    name: "{{ item }}"
    state: latest
    executable: /usr/local/bin/gem
  with_items:
    - archive-tar-minitar
    - arr-pm
    - backports
    - cabin
    - childprocess
    - clamp
    - ffi
    - fpm
    - json
    - pleaserun
    - ruby-xz
