---

- name: Install ntp
  tags:
    - ntp
  yum:
    name: ntp
    state: present

# - name: Enable/start NTP
#   tags:
#     - ntp
#   service:
#     name: ntp
#     state: started
#     enabled: yes

- name: Configure NTP
  tags:
    - ntp
  command: ntpdate pool.ntp.org
