---

# We now have the default Python installed, plus Python 2.7.x and 3.5.x which support TLS 1.1 and 1.2 connections.
- name: Install Python packages
  tags:
    - python
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python27-devel
    - python3-devel

# Let's make sure that all installed versions of Python have pip installed.
- name: Install Pip
  tags:
    - python
  shell: "wget https://bootstrap.pypa.io/get-pip.py -O - | {{ item }}"
  with_items:
    - /usr/bin/python
    - /usr/local/bin/python2.7
    - /usr/local/bin/python3.6

- name: Install Pip packages
  tags:
    - python
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - awscli

- name: Configure the AWS completer
  tags:
    - python
    - aws
  lineinfile:
    dest: /etc/bashrc
    line: "complete -C aws_completer aws"
    state: present
